In [1]:
import numpy as np

# generate random matrix
A = np.random.rand(3,3)
print(A)

[[0.53330919 0.77739023 0.01433958]
 [0.57604292 0.28674447 0.41432747]
 [0.65810509 0.95629571 0.67837906]]


In [2]:
b=A[:,0]
print(b)

[0.53330919 0.57604292 0.65810509]


In [3]:
b[0]=1

In [4]:
print(A)
print(b)

[[1.         0.77739023 0.01433958]
 [0.57604292 0.28674447 0.41432747]
 [0.65810509 0.95629571 0.67837906]]
[1.         0.57604292 0.65810509]


In [6]:
a = [[1],2,3]
b = a[0:2]
b[0][0] = 5
print(a)

[[5], 2, 3]


In [5]:
import numpy as np

# create a 3x3 array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# create a new array with the same data but a different shape
b = a.view(np.int64).reshape(9, 1)

# print the arrays
print(a)
print(b)

# modify the new array
b[0, 0] = 10

# print the arrays again
print(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[10]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]]


In [6]:
type(a)

numpy.ndarray

In [7]:
type(b)

numpy.ndarray

In [8]:
b[4]=100
print(a)

[[ 10   2   3]
 [  4 100   6]
 [  7   8   9]]


In [10]:
print(id(b))
print(id(a))

140639630540112
140639823116304


In [12]:
b.base is a

True

In [13]:
a

array([[ 10,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [16]:
c = a.diagonal()
c[2] = 111
print(a)

ValueError: assignment destination is read-only

In [20]:
import numpy as np

# create a 3x3 matrix
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# create a non-read-only view of the diagonal
b = np.diagonal(a)
b.setflags(write=True)

# modify the view and print the original matrix
b[:] = 10
print(a)


[[10  2  3]
 [ 4 10  6]
 [ 7  8 10]]
