In [1]:
import numpy as np

# generate random matrix
A = np.random.rand(3,3)
print(A)

[[0.53330919 0.77739023 0.01433958]
 [0.57604292 0.28674447 0.41432747]
 [0.65810509 0.95629571 0.67837906]]


In [2]:
b=A[:,0]
print(b)

[0.53330919 0.57604292 0.65810509]


In [3]:
b[0]=1

In [4]:
print(A)
print(b)

[[1.         0.77739023 0.01433958]
 [0.57604292 0.28674447 0.41432747]
 [0.65810509 0.95629571 0.67837906]]
[1.         0.57604292 0.65810509]


In [6]:
a = [[1],2,3]
b = a[0:2]
b[0][0] = 5
print(a)

[[5], 2, 3]
