# Úkoly

## Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [1]:
import numpy as np
a = np.arange(1,11)
print(a)
b = np.random.randint(1,10,(3,3))
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[7 8 4]
 [7 6 9]
 [7 6 1]]



1. Vyberte z pole `a` třetí a čtvrtý prvek.


In [ ]:
a[2:4]

array([3, 4])


2. Vyberte z pole `a` všechny sudá čísla.


In [5]:
a[1::2]

array([ 2,  4,  6,  8, 10])

In [6]:
b[b%2==0]

array([6, 2, 4, 2, 4])


3. Obraťte vektor `a` (první prvek se stane posledním).


In [7]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])


5. Vyberte z pole `b` druhý řádek.


In [8]:
b[1]

array([3, 4, 2])


6. Vyberte z pole `b` diagonální prvky.


In [9]:
np.diag(b)

array([6, 4, 4])

In [10]:
np.diagflat(np.diag(b))

array([[6, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])


7. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.


In [11]:
b[1,0] = 100
print(b)

[[  6   5   2]
 [100   4   2]
 [  7   5   4]]



8. Vyberte z pole `b` všechny prvky větší než 5.


In [12]:
b[b>5]

array([  6, 100,   7])


9. Vytvořte masku pro pole `b`, která bude True pro všechny prvky menší než 3.


In [13]:
b<3

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])


10. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.




In [14]:
b[b<3]

array([2, 2])


## View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [15]:
a = np.random.randint(1,10,(3,3))
print(a)

[[6 3 5]
 [4 8 1]
 [1 7 7]]



1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.


In [16]:
b = a[1,:]
print(b)

[4 8 1]



3. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?


In [17]:
b[0] = 100
print(b)
print(b.base)

[100   8   1]
[[  6   3   5]
 [100   8   1]
 [  1   7   7]]



4. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.


In [18]:
c = a[1,:].copy()
print(c.base)

None



5. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?


In [19]:
c[0] = 200
print(c)
print(a)

[200   8   1]
[[  6   3   5]
 [100   8   1]
 [  1   7   7]]



6. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.


In [20]:
print(id(b.base))
print(id(c))

131623434201936
131623434202992


In [3]:
import numpy as np

In [4]:
a = np.random.randint(1,10,(3,3))
b = a[1,:]
c = a[1,:].copy()

print(a.data)
print(b.data)
print(c.data)


In [5]:
tmp1 = a.data
tmp2 = b.data
tmp3 = c.data


In [6]:

print(tmp1)
print(tmp2)
print(tmp3)

In [26]:
np.shares_memory(b, c)

False

In [22]:
print(a.flags)
print(b.flags)
print(c.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False




7. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.


In [23]:
d = np.diag(a)
d

array([9, 3, 3])


8. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?



In [24]:
d.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [25]:
d[0] =  1

ValueError: assignment destination is read-only

9. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Jak je to s pamětí, jedná se o kopii nebo o "array view" ověřte pomocí atributu base.


In [ ]:
e = a.T
print(e.flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
a = np.ones((3,3), dtype=np.complex64)
print(a)
e = a.T
print(e.flags)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False





## Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [ ]:
a = np.random.randint(1,10,(5,3))
b = np.random.randint(1,10,(3,2))
print(a)
print(b)
print(a@b)

[[8 9 2]
 [5 4 7]
 [5 7 9]
 [6 3 9]
 [6 2 4]]
[[8 7]
 [1 3]
 [3 6]]
[[ 79  95]
 [ 65  89]
 [ 74 110]
 [ 78 105]
 [ 62  72]]


2. Vezměme náhodnou matici 10x2 představující kartézské souřadnice, převeďte je na polární souřadnice.


In [ ]:
a = np.random.rand(10,2)
print(a)
a_i = a[:,0] + a[:,1]*1j
print(a_i)
r = np.abs(a_i)
phi = np.angle(a_i)
print(f"r = {r}, phi = {phi}")

[[0.98803284 0.05719804]
 [0.7739935  0.10357581]
 [0.65953392 0.92551501]
 [0.15198932 0.56296191]
 [0.53724166 0.46697892]
 [0.51963289 0.21754081]
 [0.64143321 0.83365063]
 [0.65785829 0.56802469]
 [0.63679983 0.25787294]
 [0.9246122  0.29441915]]
[0.98803284+0.05719804j 0.7739935 +0.10357581j 0.65953392+0.92551501j
 0.15198932+0.56296191j 0.53724166+0.46697892j 0.51963289+0.21754081j
 0.64143321+0.83365063j 0.65785829+0.56802469j 0.63679983+0.25787294j
 0.9246122 +0.29441915j]
r = [0.98968707 0.78089301 1.13646955 0.58311822 0.71182717 0.56333146
 1.05186022 0.86915452 0.68703164 0.97035578], phi = [0.05782628 0.13302967 0.95165541 1.30710171 0.71554456 0.39647414
 0.9149775  0.71224819 0.38476747 0.30827312]


3. Vzhledem ke dvěma polím X a Y zkonstruujte Cauchyho matici C (Cij =1/(xi - yj)).


In [ ]:
X = np.random.rand(10,1)
Y = np.random.rand(10,1)
print(X)
print(Y)

[[0.86891032]
 [0.58406747]
 [0.54227646]
 [0.66242453]
 [0.3464448 ]
 [0.83630689]
 [0.73074155]
 [0.87366251]
 [0.38179543]
 [0.1808159 ]]
[[0.57085089]
 [0.89304499]
 [0.1337839 ]
 [0.84428532]
 [0.24877707]
 [0.5270398 ]
 [0.98853738]
 [0.58464159]
 [0.47608519]
 [0.6401538 ]]


In [ ]:
C = 1 / (X.reshape(-1, 1) - Y.reshape(1, -1))
print(C)

[[ 3.35503560e+00 -4.14341601e+01  1.36031025e+00  4.06091417e+01
   1.61255667e+00  2.92508404e+00 -8.35931250e+00  3.51779813e+00
   2.54566199e+00  4.37146012e+00]
 [ 7.56624998e+01 -3.23648142e+00  2.22082276e+00 -3.84293396e+00
   2.98248919e+00  1.75353456e+01 -2.47237182e+00 -1.74180837e+03
   9.26077829e+00 -1.78296581e+01]
 [-3.49963238e+01 -2.85088284e+00  2.44802504e+00 -3.31116110e+00
   3.40716216e+00  6.56311866e+01 -2.24084151e+00 -2.36043165e+01
   1.51077329e+01 -1.02168692e+01]
 [ 1.09201725e+01 -4.33612871e+00  1.89164424e+00 -5.49871146e+00
   2.41751756e+00  7.38635717e+00 -3.06642319e+00  1.28562892e+01
   5.36655321e+00  4.49019789e+01]
 [-4.45620716e+00 -1.82949076e+00  4.70232189e+00 -2.00867540e+00
   1.02387963e+01 -5.53725199e+00 -1.55740782e+00 -4.19820943e+00
  -7.71364562e+00 -3.40473057e+00]
 [ 3.76710256e+00 -1.76248413e+01  1.42344096e+00 -1.25337989e+02
   1.70204126e+00  3.23345101e+00 -6.56898641e+00  3.97353146e+00
   2.77606815e+00  5.09805875e+00

4. Uvažujme náhodný vektor o tvaru (100,2) představující souřadnice, najděte vzdálenosti bod po bodu.


In [ ]:
x = np.random.rand(10,2)
np.sqrt((x[:,0].reshape(-1,1) - x[:,0].reshape(1,-1))**2 + (x[:,1].reshape(-1,1) - x[:,1].reshape(1,-1))**2)

array([[0.        , 0.27711272, 0.86670366, 0.4518602 , 0.73184438,
        0.55261845, 0.54226928, 0.87480685, 0.50069181, 0.57683801],
       [0.27711272, 0.        , 0.61353699, 0.18807856, 0.58916184,
        0.33782226, 0.33988617, 0.71500496, 0.25014062, 0.58306945],
       [0.86670366, 0.61353699, 0.        , 0.53436956, 0.4236761 ,
        0.6530996 , 0.35416327, 0.40699678, 0.55780906, 0.73925192],
       [0.4518602 , 0.18807856, 0.53436956, 0.        , 0.64298221,
        0.18347878, 0.37483713, 0.74393472, 0.06998036, 0.7247053 ],
       [0.73184438, 0.58916184, 0.4236761 , 0.64298221, 0.        ,
        0.820964  , 0.26817682, 0.14618079, 0.70268349, 0.35325274],
       [0.55261845, 0.33782226, 0.6530996 , 0.18347878, 0.820964  ,
        0.        , 0.55385009, 0.91385671, 0.11840125, 0.90428752],
       [0.54226928, 0.33988617, 0.35416327, 0.37483713, 0.26817682,
        0.55385009, 0.        , 0.37879148, 0.43545193, 0.43480243],
       [0.87480685, 0.71500496, 0.4069967

In [ ]:
np.sqrt(np.sum((x.reshape(-1,1,2) - x.reshape(1,-1,2))**2, axis=2))

array([[0.        , 0.27711272, 0.86670366, 0.4518602 , 0.73184438,
        0.55261845, 0.54226928, 0.87480685, 0.50069181, 0.57683801],
       [0.27711272, 0.        , 0.61353699, 0.18807856, 0.58916184,
        0.33782226, 0.33988617, 0.71500496, 0.25014062, 0.58306945],
       [0.86670366, 0.61353699, 0.        , 0.53436956, 0.4236761 ,
        0.6530996 , 0.35416327, 0.40699678, 0.55780906, 0.73925192],
       [0.4518602 , 0.18807856, 0.53436956, 0.        , 0.64298221,
        0.18347878, 0.37483713, 0.74393472, 0.06998036, 0.7247053 ],
       [0.73184438, 0.58916184, 0.4236761 , 0.64298221, 0.        ,
        0.820964  , 0.26817682, 0.14618079, 0.70268349, 0.35325274],
       [0.55261845, 0.33782226, 0.6530996 , 0.18347878, 0.820964  ,
        0.        , 0.55385009, 0.91385671, 0.11840125, 0.90428752],
       [0.54226928, 0.33988617, 0.35416327, 0.37483713, 0.26817682,
        0.55385009, 0.        , 0.37879148, 0.43545193, 0.43480243],
       [0.87480685, 0.71500496, 0.4069967

5. Ověřte empiricky na náhodné matici, že platí $(AB)^T = B^T A^T$


In [ ]:
A = np.random.rand(10,5)
B = np.random.rand(5,3)
print(A)
print(B)
print((A@B).T)
print(B.T@A.T)
print((A @ B).T == B.T @ A.T)

[[0.69731805 0.68303335 0.07434401 0.58093047 0.39264347]
 [0.69064067 0.112283   0.92225303 0.32471131 0.4189296 ]
 [0.51626691 0.84771345 0.78224813 0.72789639 0.71079192]
 [0.57021842 0.91894117 0.02412249 0.90650778 0.56525145]
 [0.07304401 0.98193922 0.80531471 0.82804121 0.85873617]
 [0.3763278  0.18700183 0.55395799 0.21429994 0.10786688]
 [0.42018987 0.3831252  0.97109796 0.30714362 0.15125017]
 [0.22323951 0.65632206 0.44576158 0.28353503 0.68802272]
 [0.54510385 0.68125025 0.25611076 0.37486769 0.43588984]
 [0.87306317 0.92943934 0.07308184 0.01177656 0.74349406]]
[[0.61527061 0.76853034 0.99405561]
 [0.03165951 0.33442653 0.00270984]
 [0.50332861 0.68561573 0.25228467]
 [0.41696431 0.70687526 0.59617376]
 [0.22351645 0.40418218 0.61895979]]
[[0.81807282 1.12171276 1.20059043 0.89639779 1.01857279 0.62975217
  0.92131625 0.65450449 0.7395973  0.77447344]
 [1.38465084 1.59949418 2.01840765 1.6313397  1.8690672  0.92664121
  1.39510078 1.17518942 1.26351417 1.34074237]
 [1.3031

In [ ]:
np.isclose((A @ B).T, B.T @ A.T, rtol=1e-6)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
np.allclose((A @ B).T, B.T @ A.T, rtol=1e-6)

True

6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$ $$(uv)_{ij} = u_iv_j$$ pomocí `newaxis`. Zkontrolujte s `np.outer(u, v)`


In [ ]:
u = np.random.randint(1,10,(10,1))
v = np.random.randint(1,10,(10,1))
print(u.reshape(-1,1) @ v.reshape(1,-1))
print(np.outer(u,v))


[[10 10 15 35  5 20 10 25  5 20]
 [ 2  2  3  7  1  4  2  5  1  4]
 [ 8  8 12 28  4 16  8 20  4 16]
 [10 10 15 35  5 20 10 25  5 20]
 [ 6  6  9 21  3 12  6 15  3 12]
 [ 6  6  9 21  3 12  6 15  3 12]
 [16 16 24 56  8 32 16 40  8 32]
 [16 16 24 56  8 32 16 40  8 32]
 [16 16 24 56  8 32 16 40  8 32]
 [ 8  8 12 28  4 16  8 20  4 16]]
[[10 10 15 35  5 20 10 25  5 20]
 [ 2  2  3  7  1  4  2  5  1  4]
 [ 8  8 12 28  4 16  8 20  4 16]
 [10 10 15 35  5 20 10 25  5 20]
 [ 6  6  9 21  3 12  6 15  3 12]
 [ 6  6  9 21  3 12  6 15  3 12]
 [16 16 24 56  8 32 16 40  8 32]
 [16 16 24 56  8 32 16 40  8 32]
 [16 16 24 56  8 32 16 40  8 32]
 [ 8  8 12 28  4 16  8 20  4 16]]


7. Vypočítejte hodnost matice o velikosti 5x6 naplněnou hodnotami 0, 1, 2, 3 ... . Byly by jste schopni zdůvodnit proč je hodnost taková jaká je?


In [ ]:
A = np.arange(0,30).reshape(5,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
np.linalg.matrix_rank(A)

np.int64(2)


## Funkce nad poli
1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.


In [ ]:
a = np.random.randint(1,10,(10,10))
print(a)
print(a.max())
print(a.min())

[[1 7 4 7 9 8 7 2 9 8]
 [9 3 4 3 8 7 3 7 7 8]
 [6 8 8 5 8 4 5 3 6 5]
 [6 8 2 5 1 1 2 5 5 6]
 [9 3 3 9 6 5 8 3 7 3]
 [4 6 6 9 1 7 5 8 1 9]
 [7 7 5 1 8 4 6 3 3 4]
 [1 1 1 1 3 5 7 7 7 6]
 [9 6 3 7 5 6 1 5 8 6]
 [9 9 8 8 6 5 9 5 4 3]]
9
1


In [ ]:
np.min(a, axis=0)

array([1, 1, 1, 1, 1, 1, 1, 2, 1, 3])

2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.



In [ ]:
b = np.random.rand(30)
np.mean(b)

np.float64(0.48658403702840836)

3. Uvažujme celočíselný vektor Z, které z těchto výrazů jsou platné?
   ```python
   Z**Z
   2 << Z >> 2
   Z <- Z
   1j*Z
   Z/1/1
   Z<Z>Z
   ```



In [ ]:
Z = np.random.randint(1,10,(10,1))

Z**Z


array([[        1],
       [        4],
       [     3125],
       [        1],
       [   823543],
       [       27],
       [387420489],
       [ 16777216],
       [        1],
       [   823543]])

In [ ]:
Z

array([[1],
       [2],
       [5],
       [1],
       [7],
       [3],
       [9],
       [8],
       [1],
       [7]])

In [ ]:
2 << Z >> 2


array([[  1],
       [  2],
       [ 16],
       [  1],
       [ 64],
       [  4],
       [256],
       [128],
       [  1],
       [ 64]])

In [ ]:
Z < (-Z)


array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [ ]:
1j*Z


array([[0.+1.j],
       [0.+2.j],
       [0.+5.j],
       [0.+1.j],
       [0.+7.j],
       [0.+3.j],
       [0.+9.j],
       [0.+8.j],
       [0.+1.j],
       [0.+7.j]])

In [ ]:
Z/1/1


array([[1.],
       [2.],
       [5.],
       [1.],
       [7.],
       [3.],
       [9.],
       [8.],
       [1.],
       [7.]])

In [ ]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

4. Jaký je výsledek následujícího výrazu? 
   ```python
   0 * np.nan
   np.nan == np.nan
   np.inf > np.nan
   np.nan - np.nan
   np.nan in set([np.nan])
   0.3 == 3 * 0.1
   ```


In [ ]:
0 * np.nan


nan

In [ ]:
np.nan == np.nan


False

In [ ]:
np.isnan(np.nan)

np.True_

In [ ]:
np.inf

inf

In [ ]:
np.inf > np.nan


False

In [ ]:
np.nan - np.nan


nan

In [ ]:
np.nan in set([np.nan])


True

In [ ]:
0.3 == 3 * 0.1

False

In [ ]:
0.3

0.3

In [ ]:
3*0.1

0.30000000000000004

5. Jaké jsou výsledky následujících výrazů?
   ```python
   np.array(0) / np.array(0)
   np.array(0) // np.array(0)
   np.array([np.nan]).astype(int).astype(float)
   ```


In [ ]:
np.array(0) / np.array(0)


/tmp/ipykernel_5910/3272234849.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [ ]:
np.array(0) // np.array(0)


/tmp/ipykernel_5910/474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [ ]:
np.array([np.nan]).astype(int)

/tmp/ipykernel_5910/3091100680.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int)


array([-9223372036854775808])


6. Jak najít společné (stejné) hodnoty mezi dvěma poli? 


In [2]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[6 1 1]
 [4 6 1]
 [7 5 7]]
[[5 7 9]
 [6 9 1]
 [2 4 2]]


In [3]:
# find the common elements and their indices in a and b
a_flat = a.flatten()
b_flat = b.flatten()
common_elements = np.intersect1d(a_flat, b_flat)
indices_a = np.where(np.isin(a_flat, common_elements))[0]
indices_b = np.where(np.isin(b_flat, common_elements))[0]
print("Common elements:", common_elements)
print("Indices in a:", indices_a)
print("Indices in b:", indices_b)

Common elements: [1 4 5 6 7]
Indices in a: [0 1 2 3 4 5 6 7 8]
Indices in b: [0 1 3 5 7]



7. Jak vypočítat ((A+B)*(-A/2)) přímo v poli (bez kopírování)?



In [5]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
# compute ((A + B) * (-A / 2)) inplace
print(((A + B) * (-A / 2)))

np.add(A, B, out=B)
np.multiply(A, -0.5, out=A)
np.multiply(A, B, out=A)
print(A)

[[-0.49665044 -0.48483555 -0.25503963]
 [-0.54341387 -0.32442104 -0.01002972]
 [-0.07552486 -0.20322928 -0.21594062]]
[[-0.49665044 -0.48483555 -0.25503963]
 [-0.54341387 -0.32442104 -0.01002972]
 [-0.07552486 -0.20322928 -0.21594062]]



8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.


In [7]:
a = np.random.rand(10)
print(np.sort(a))
print(np.argsort(a))
print(a[np.argsort(a)])

[0.04675613 0.05252181 0.05551575 0.3283658  0.42680773 0.61822348
 0.74122679 0.78330901 0.81652744 0.96143675]
[1 6 5 4 7 2 0 8 3 9]
[0.04675613 0.05252181 0.05551575 0.3283658  0.42680773 0.61822348
 0.74122679 0.78330901 0.81652744 0.96143675]



9. Vezměme daný vektor, jak přidat 1 ke každému prvku indexovanému druhým vektorem (dejte pozor na opakované indexy)? 



In [10]:
values = np.zeros(5)
indices = np.random.randint(0, 5, 10)


In [9]:
values[indices] += 1
print(values)

[0. 1. 1. 1. 1.]


In [11]:
print(indices)
np.add.at(values, indices, 1)
print(values)

[3 4 0 4 0 4 1 4 0 3]
[3. 1. 0. 2. 4.]
